# Generated by Django 4.2.3 on 2023-07-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
